CREATE TABLE CUSTOMER (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE TRANSACTION (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    CUS_ID BIGINT NOT NULL,
    TRANSACTION_DATE DATETIME(6) NOT NULL,
    TRANSACTION_AMOUNT DECIMAL(5,2),
    PRIMARY KEY (ID),
    FOREIGN KEY (CUS_ID) REFERENCES CUSTOMER (ID)
    );